### PR TITLE
Allow Uint8Array passphrases

### PR DESCRIPTION
**Pull request by JDinABox**
Implements proposal from #579

### CODE REVIEW

**Comment by twiss** [comment]
Hello :wave: Sorry for the delay, and thanks for the PR!

May I ask what's your use case for this? Is it primarily performance? (If so, I'm somewhat skeptical of the performance gains, as this immediately precedes the "string-to-key" (S2K) password hashing, which is much slower.)

**Comment by JDinABox** [comment]
Hi, thanks for the reply.

This PR is primarily to allow non-string passphrases (For instance, a passphrase already run through a KDF) to be passed as values without increasing complexity with encoding.
I agree that the performance benefits are negligible compared to the S2K's cost.

**Comment by twiss** [comment]
I see, thanks. The issue is that the passphrase is really meant to be a string (it's even called "string-to-key" :sweat_smile:), and I believe for example GnuPG also only supports passing passphrases as a string, and encodes it as UTF-8. So - it may be better to just encode the key as a string (e.g. base64 or hex), so that you don't run into issues with other libraries later.

**Comment by JDinABox** [comment]
Okay, that makes sense.
Thanks for taking a look at this, closing.

**Pull request closed without merging**
