### PR TITLE
Fix unit tests on Safari, Closes openpgpjs/openpgpjs#399

### PR DESCRIPTION
**Pull request by tanx**

### CODE REVIEW

**Comment by evilaliv3** [comment]
great!maybe we would like to test 4096 on all browsers except on safari?

**Comment by tanx** [comment]
> great!maybe we would like to test 4096 on all browsers except on safari?

Please not on travis. I'm glad they're running really fast now. 43 seconds for node v5 ;)

https://travis-ci.org/openpgpjs/openpgpjs/builds/106728025

**Comment by evilaliv3** [comment]
okay ;)

**Comment by tanx** [comment]
Beautiful. The current version of all platform are now green! iOS and Android included:

https://github.com/openpgpjs/openpgpjs

**Comment by evilaliv3** [comment]
yes probably iOS was failing due of safary;
i dot know instead what fixed android.

**Pull request merged**
