### PR TITLE
Improve unit testing by means of Coveralls and Saucelabs

### PR DESCRIPTION
**Pull request by evilaliv3**
This pull request implement support for issues #313 and #314

- #313: Each unit test is now performed on SauceLabs.com in order to do on-commit cross-browser testing.
- #314 Code coverage is now monitored in the cloud on-commit by means of Coveralls.io;

An execution of the current .travis.ci script is available at: https://travis-ci.org/evilaliv3/openpgpjs

### CODE REVIEW

**Comment by tanx** [comment]
Very cool. Thanks!

Any idea why the travis build fails?

**Comment by evilaliv3** [comment]
let me check

**Comment by evilaliv3** [comment]
sure tanx!

grunt saucelabs return false if there is at least one browser that is failing the test.
in the short term we can put "grunt saucelabs || true"

the real good solution would be to monitor only the  browsers/version/os for openpgp.js and put only them under monitoring.
e.g. using caniuse.com/#search=crypto

screenshot from 2015-05-11 11 40 15

as you can see:
- i did put ie8, ie9, ie10 just for test but we already know that webcrypto is not supported here.
- safari is failing and we should see why: https://saucelabs.com/tests/95a439f819a348cd88079077c7e7dad7 and eventually opening a issue and fix it
- iphone is failing
- i didnt put any ipad (saucelabs offers also this)
- i did not put any android (it would be really valuable to test against it)

here is an omnicomprensive list of the tests supporde by saucelabs, i'm going to investigate the relevant ones for openpgp.js an i will be back here: https://github.com/globaleaks/GlobaLeaks/blob/536435c60ad4ccb47d60094a556852ed9c9a499f/scripts/travis_saucelabs.sh

**Comment by tanx** [comment]
iOS and Safari are failing because the native RSA keygen via WebCrypto will not accept a keysize smaller than 2048. If you set the keysize to 2048 in the test it should work. Although we might have to increase the timeout for that test:

https://github.com/openpgpjs/openpgpjs/blob/master/test/general/basic.js#L12

Also, is there any way you can give me access to the saucelabs instance so I can maintain changes in the future?

**Comment by tanx** [comment]
And feel free to remove IE version older than 11.

**Comment by evilaliv3** [comment]
right suggestions, i'm working on them and i will be back when all is ready for the clean integration.

**Comment by evilaliv3** [comment]
sure tankred, when finished setting it up allo i'll pass the saucelab credentials.

**Comment by evilaliv3** [comment]
ok @tanx  we are all set:

https://travis-ci.org/evilaliv3/openpgpjs
https://saucelabs.com/u/openpgpjs

in the end i've decided to not put safari under unit testing for the moment.
the reason is that as you said the key bit len should be raised to 2048.
this makes in general all unit tests to last longer, and in the specific cases of IE and Safari it makes saucelabs provide errors due to very big timeouts.

the latest selection is so the follwing:
tested browsers: IE, Chrome, Firefox
the stable version is tested on all OS
all the other relevant versions are tested only in the main native OS

screenshot from 2015-05-12 13 14 13

**Comment by tanx** [comment]
> in the end i've decided to not put safari under unit testing for the moment.
> the reason is that as you said the key bit len should be raised to 2048.
> this makes in general all unit tests to last longer, and in the specific cases of IE and Safari it makes saucelabs provide errors due to very big timeouts.

I've enabled 2048 bit keys only in case of WebCrypto support here: https://github.com/openpgpjs/openpgpjs/commit/85133393e3f79c21bd51a2e1a72730a9138ce2de

This will not slow down browsers without webcrypto support like IE. If you rebase your PR on top of the current master you should be able to add iOS, Android and Safari to the test suite once again.

**Comment by tanx** [comment]
Any update on this? Looking forward to cross-browser CI. Thanks again for your work.

**Comment by evilaliv3** [comment]
i think we are done https://saucelabs.com/u/openpgpjs
https://github.com/evilaliv3/openpgpjs/tree/feature/unittesting

i've now commited the addition of all the browsers that support WebCrypto and that are on Saucelabs; let's see the results.

given the fact that we can add to the test whatever configuration (due to time limits) what are the rilevant browsers/version that we want to test among the one that does not support WebCrypto?

**Comment by evilaliv3** [comment]
screenshot from 2015-05-21 14 38 09

Ok @tanx i think we are done and this is the status:
- tests succeed on every browser version that support webcrypto (and that is present on saucelabs) for: firefox, chrome, ie
- tests fails due to browser exploding on Android 5.1 (the one with chrome 42) runned on the linux emulator in one of the first tests (screencas available here: https://saucelabs.com/tests/a68371abf5e24fc7a41c713d093df537)
- tests fails on all OSX/IOS due probably to a current outage of saucelabs.

i've put all this tests in .travis.yml with a || true, this way we can track them without not impacting on the global badge failure/success.

fine to proceed for the merging for me.

\cc @fpietrosanti

**Comment by evilaliv3** [comment]
@tanx @AlexanderWillner: except from the browsers that support webcrypto on wich other is OpenPGP expected to work? 

because  probably we should write the tests so that we test also the "config.useWebCrypto == false" condition so to test also what happens (on all the browsers) whenever the web crypto is not enabled or not present. if you can go over mergin this patch i promise to tackle this task! as it's also needed from us in globaleaks so i'm really intested to work on this topic for openpgpjs

\cc @fpietrosanti

**Comment by fpietrosanti** [comment]
@tanx Do you have a list of OpenPGP.js practically supported with/webcrypto browsers/osx pair based on your experience? So that we can declare officially a supported listed list and invest time required to make all tests pass on those platforms where we know that OpenPGP.js works but the tests, for some reasons, need to re-organized

**Comment by tanx** [comment]
Whiteout runs on Chrome, Firefox, Safari 8+, IE11, Android 4.0+ (Crosswalk WebView) and iOS 8.0+. We've got a pre-alpha Windows 8 and Firefox OS App running in our lab.

**Comment by evilaliv3** [comment]
this cause it probably enforces the use of webCrypto.

by using "config.useWebCrypto == false"  is it still compatible with some browser? if yes what are them?

**Comment by tanx** [comment]
> this cause it probably enforces the use of webCrypto.
> 
> by using "config.useWebCrypto == false" is it still compatible with some browser? if yes what are them?

Sorry I don't quite understand. Do you want to run the tests once with webcrypto activated and once without? Yes, you could do that by setting `openpgp.config.useWebCrypto = false`.

The only hard dependency for OpenPGP.js is `window.crypto.getRandomValues()`.

**Comment by tanx** [comment]
> i've put all this tests in .travis.yml with a || true, this way we can track them without not impacting on the global badge failure/success.

GitHub tells me I can't merge automatically. Could you rebase on top of the current master?

**Comment by evilaliv3** [comment]
rebased but concerning your comment:
> Sorry I don't quite understand. Do you want to run the tests once with webcrypto activated and once without? Yes, you could do that by setting openpgp.config.useWebCrypto = false.

> The only hard dependency for OpenPGP.js is window.crypto.getRandomValues().

let's wait for today and i will make a patch that will make us possible to test openpgp even with only this requirement: window.crypto.getRandomValues()

**Comment by evilaliv3** [comment]
ah ok, no changes are needed in the unit tests. already openpgp does backword compatibility atuomagically.

screenshot from 2015-05-21 19 57 22

**Comment by evilaliv3** [comment]
here we are @tanx !
no change is needed to the test, and thanks to saucelabs we spotted some failures on Safari, and Android

i do not know why github say that the build is failing: https://travis-ci.org/evilaliv3/openpgpjs/builds/63523435

ok for me to proceed with the merge.

**Comment by tanx** [comment]
Don't know why the build is failing either but I'd like to wait with the merge until we have CI working again:
https://travis-ci.org/openpgpjs/openpgpjs/builds/63523438

N.B. I will be off the grid for the next two weeks. I'll look at this once I'm back or perhaps @toberndo can take a look in the meantime? thx

**Comment by evilaliv3** [comment]
i've pusshed not a commit in order to trigger a need build.

**Comment by evilaliv3** [comment]
ah! it is failing due to the fact that the keys for saucelabs where still encrypted for my repository. now it should work like a charm.

**Comment by tanx** [comment]
Still seems to be failing: https://travis-ci.org/openpgpjs/openpgpjs/builds/63622271#L327

**Comment by tanx** [comment]
FYI we finally have WebCrypto support for IE11 in https://github.com/openpgpjs/openpgpjs/pull/296 so the cross browser tests should really come in handy :+1:

**Comment by evilaliv3** [comment]
i know @tanx let me redo a push just to trigger the build an other time. 
if it wont work it means that i should ask saucelabs to move the saucelabs account to openpgp/js repository (now credentials are binded to mine)

**Comment by evilaliv3** [comment]
ok @tanx i've undestood why the build was failing.
travis does not support encrypted keys on pull request; now all unit tests should work.

when merging revert last commit and put the following inside .travis.yml:

    env:
      global:
        - secure: a3JyzGFVcoK6OqTf6g6Esf1OZlj7qhe9yv/dJPN9QEfHcEztvJAUHkpxvugsZPf2eTTZoFdD+stkLWvmAjPEqE9SLGrqAp9foQLF/MwvEd6gywO/c8Yx1rZ2JwQiTvFy9RKzKXHjx50h8fMTsrvyBhsd8WCkWXXn66FW+oZwnro=
        - secure: KMpqNgNDV9URoyxVNFHWgMPHB/P9Qb+dvX1ZVLh7J4LaVrLwkwBcwR94zkY9EnAtjK7gJd9lLDNOVhfWEayH6OGaxpu28vDeLLvsSLIw49bpYhdj6xVpheaaBv5MWz2itpkN+PmBAZwjgyuoLyriBNLgVjJaHVsh2vUj5C54D1Y=

the patch is already rebased for current master

https://saucelabs.com/u/openpgpjs

**Pull request merged**
