### PR TITLE
put `sudo: false` in `.travis.yml`

### PR DESCRIPTION
**Pull request by Mithgol**
May reduce the time of Travis CI testing as mentioned by @toberndo at https://github.com/openpgpjs/openpgpjs/pull/375#issuecomment-160397424.

### CODE REVIEW

**Comment by Mithgol** [comment]
The time of testing on Travis CI for Node.js version 0.12.2 is significanlty improved (34:59 in [build 580](https://travis-ci.org/openpgpjs/openpgpjs/builds/93761411) compared to 42:58 in [build 579](https://travis-ci.org/openpgpjs/openpgpjs/builds/93733300)).

Node.js v4.2 testing fails, but not with the previous `Your test run exceeded 50 minutes.`; it's only `Aborted due to warnings.`

Therefore I recommend accepting this pull request.

**Comment by evilaliv3** [comment]
merged manually, see: https://github.com/openpgpjs/openpgpjs/commit/46d2b6e66da9021e3e18d01a443aa3d4940ce402

**Comment by Mithgol** [comment]
The changes in 46d2b6e66da9021e3e18d01a443aa3d4940ce402 do not seem to include any `sudo`.

**Comment by Mithgol** [comment]
Oh, I see. My line of code has been merged in 0e8cedae46d3df19bca8331394ca1771120d1c56.

**Pull request closed without merging**
