### PR TITLE
Comment typo fixes

### PR DESCRIPTION
**Pull request by kAworu**

### CODE REVIEW

**Comment by chesnokovilya** [comment]
Thank you!

**Comment by chesnokovilya** [comment]
Seem good, we could merge this soon. If you are interested here are other issues with docs like this https://github.com/openpgpjs/openpgpjs/issues/669

**Comment by twiss** [comment]
Thanks! :thanks: And happy holidays :blush:

**Comment by kAworu** [comment]
@twiss @chesnokovilya  Happy holidays to you both :)

**Pull request merged**
