### PR TITLE
implement keyExpirationTime

### PR DESCRIPTION
**Pull request by dpjanes**
This implements keyExpirationTime when generating a new key. 

This is more or less a 2.x port of https://github.com/openpgpjs/openpgpjs/pull/458/files

See also: https://github.com/openpgpjs/openpgpjs/issues/511

### CODE REVIEW

**Comment by bartbutler** [comment]
Thanks! Can you remove the dist files from your commit please?

**Comment by dpjanes** [comment]
It's not at all obvious to me how to do this, as the dist files are checked in on your master and they're automatically built as part of any testing process I run?

**Comment by dpjanes** [comment]
OK, I think I have it: I copied the versions that you had checked in on top of mine. Should be good to go.

**Comment by bartbutler** [comment]
Looks good, thanks!

**Pull request merged**
