### PR TITLE
Fix merging multiple subkey binding signatures

### LINKED ISSUE #863: SubKey.prototype.update overwrites newer binding signature
We got an issue where subkey binding signatures are not merged correctly when using the Key.prototype.update method. I think the line `that.bindingSignatures[i] = srcBindSig;` at https://github.com/openpgpjs/openpgpjs/blob/master/src/key.js#L1187 has to be omitted. The `checkFn`of `mergeSignatures` should only return true or false but not change the signatures. And the purpose of the for loop at https://github.com/openpgpjs/openpgpjs/blob/master/src/key.js#L1184 is to determine if a binding signature on the destination key has a newer creation date as on the source  key in which case we do not need to merge.

### PR DESCRIPTION
**Pull request by toberndo**
Fixes #863

### CODE REVIEW

**Comment by twiss** [comment]
Hi @toberndo! Thanks for the PR, and sorry for the delay.

I imagine what the code should be doing is something like: "If a binding signature from the same key already exists, don't add it to the list. If the one in the passed key is newer, overwrite it." If that's correct, I think the patch should instead be something like:

```patch
       if (that.bindingSignatures[i].issuerKeyId.equals(srcBindSig.issuerKeyId)) {
-        if (srcBindSig.created < that.bindingSignatures[i].created) {
+        if (srcBindSig.created > that.bindingSignatures[i].created) {
           that.bindingSignatures[i] = srcBindSig;
-          return false;
         }
+        return false;
       }
```

However, that makes your test fail, unless I also change

```patch
-      expect(dest.subKeys[0].bindingSignatures.length).to.equal(2);
+      expect(dest.subKeys[0].bindingSignatures.length).to.equal(1);
```

So I might be wrong. Is there some reason the result should have two binding signatures?

**Comment by toberndo** [comment]
> "If a binding signature from the same key already exists, don't add it to the list. If the one in the passed key is newer, overwrite it."

You are right, I think that's the way it should be. Actually we tested with Kleopatra and on merge here also only the newest binding signature is preserved. I don't see a reason to keep the older signature in the key.

Would you like me to change the PR? Or, if you have the change already done, please go on.

**Comment by twiss** [comment]
Yeah, could you update this PR, please? Thanks!

**Comment by toberndo** [comment]
@twiss Done :)

**Pull request merged**
